[package]
name = "storage-sqlite"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
storage = { path = "../storage" }
domain = { path = "../domain" }
sqlx = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
