[package]
name = "quran-search"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
domain = { path = "../domain" }
quran-core = { path = "../quran-core" }
quran-normalization = { path = "../quran-normalization" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
regex-automata = { workspace = true }
sqlx = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
proptest = { workspace = true }
